### PR TITLE
Travis: optimize to run coverage only once

### PR DESCRIPTION
**Pull request by TomasVotruba**
Well the optimalization has no influence, since 90% of time takes `composer update`.
So this can be closed I guess

Anyway, is there some reason use two phpunits?

### CODE REVIEW

**Comment by Ocramius** [comment]
@TomasVotruba the point of the second (performance) run is to run with `php -n`, which is vital, since XDebug would otherwise defeat the entire point of it.

**Comment by Ocramius** [comment]
Thanks, merged!

**Comment by TomasVotruba** [comment]
Thank you!

I'm not sure I understand.

I meant one PHPUnit in travis and one from composer. How do they differ?

- sh -c "if [ '$TRAVIS_PHP_VERSION' = '5.3.3' ]; then **phpunit**; fi"
- sh -c "if [ '$TRAVIS_PHP_VERSION' != '5.3.3' && '$TRAVIS_PHP_VERSION' != '5.6' ]; then **./vendor/bin/phpunit**; fi"

**Comment by Majkl578** [comment]
In version I suppose, first one is from PEAR repo.

**Comment by TomasVotruba** [comment]
Both are `~4.0`, right?

But actually some shell commands are never run, they [silently fail at syntax](https://travis-ci.org/Ocramius/Instantiator/jobs/46762013#L144). I'll prepare fix.

**Pull request merged**
